# Generated by Django 2.0.4 on 2018-04-07 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dir_name', models.CharField(max_length=30)),
                ('no_of_files', models.IntegerField(max_length=50)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=30)),
                ('file_size', models.IntegerField(max_length=9999999999)),
                ('file_type', models.CharField(max_length=10)),
                ('dir_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.Directory')),
            ],
        ),
    ]
