# Generated by Django 2.0.4 on 2018-04-07 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='no_of_files',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='files',
            name='file_size',
            field=models.IntegerField(),
        ),
    ]
