# Generated by Django 2.0.4 on 2018-04-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20180407_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='file_size',
        ),
        migrations.AddField(
            model_name='files',
            name='file',
            field=models.FileField(default='files/media/group_Deerwalk.jpg', upload_to=''),
        ),
    ]
