# Generated by Django 2.0.4 on 2018-04-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_auto_20180409_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(default='files/media/group_Deerwalk.jpg', upload_to='<django.db.models.fields.related.ForeignKey>media/'),
        ),
    ]
