# Generated by Django 2.0.4 on 2018-04-09 13:29

from django.db import migrations, models
import files.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_auto_20180409_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='dir_name',
            new_name='dir',
        ),
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(upload_to=files.models.get_file_path),
        ),
    ]
