# Generated by Django 2.0.4 on 2018-04-09 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_auto_20180409_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='dir',
        ),
        migrations.DeleteModel(
            name='Files',
        ),
    ]
