# Generated by Django 2.0.4 on 2018-04-10 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0009_auto_20180409_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directory',
            name='no_of_files',
        ),
    ]
