# Generated by Django 2.0.4 on 2018-04-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0010_remove_directory_no_of_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
