# Generated by Django 2.0.4 on 2018-04-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0011_auto_20180410_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='description',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
